# -*- coding: utf-8 -*-
"""Day 6 machine learning workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGFhEd6Wr8C2HS3_HxEIF3nRd9gEnOw9

**Machine learning DAY 6**

step 1: import Data
step 2: Prepare Data
step 3: split Data
step 4: Train Data
step 5: predict Data
"""

!pip install scikit-learn

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

from sklearn.datasets import load_iris, load_digits

#create dataset
data={
    'hours_studied':[1,2,3,4,5,6,7,8,9,10],
    'pass_fail':[1,0,1,0,1,0,1,0,1,0]
}
df=pd.DataFrame(data)
print(df)

from sklearn import model_selection
from ast import mod
#separate feature
x=df[["hours_studied"]]
y=df["pass_fail"]
#split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
#predict
print(f'Train:{len(x_train)} rows| Test: {len(x_test)}rows')
#create dataset and train
model=LogisticRegression()
model.fit(x_train,y_train)
print("model trained suceesfully")
 #evaluate on test set
y_pred =model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy*100:.2f}%')
print("Classification Report:")
print(classification_report(y_test,y_pred,
                            target_names=['pass','fail']))

print(df)

new_students=[[20],[1],[50]]
predictions=model.predict(new_students)
labels={0:'fail',1:'pass'}
for hrs,pred in zip(new_students,predictions):
  print(f'studied{hrs[0]} hrs-> {labels[pred]} ')